"""Persistence boundary for runtime and operator inspection."""

from typing import Protocol

from app.core.models import AgentDefinition, Event, Run
from app.orchestration.workflow import WorkflowDefinition


class Repository(Protocol):
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def register(
        self, agents: list[AgentDefinition], workflows: list[WorkflowDefinition]
    ) -> None: ...
    async def save(self, run: Run, events: list[Event], expected_revision: int) -> None: ...
    async def get(self, run_id: str) -> Run: ...
    async def events(self, run_id: str) -> list[Event]: ...
    async def replay(self, run_id: str, revision: int) -> Run: ...
